language: swift
osx_image: xcode12.2
cache:
    bundler: true
    cocoapods: true
before_install:
  - yes | gem update --system --force
  - gem install bundler
install:
    - bundle install
    - bundle exec pod install
    - brew install libsodium
script:
  - bundle exec fastlane build_for_testing